services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: user-app
    user: ${UID}:${GID}
    restart: unless-stopped
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    working_dir: /var/www
    depends_on:
      - db
      - frontend
      
  frontend:
    container_name: user-frontend
    build: .
    ports:
      - "5173:5173"
    command: npm run dev
    volumes:
      - .:/var/www/html
