version: "3.9"

services:
  app:
    container_name: app
    image: nyck1sha/crud-laravel:1.0.0
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata16:/var/lib/postgresql/data

volumes:
  pgdata16: {}
    