---
- name: Deploy Laravel application to Yandex Cloud
  hosts: 158.160.132.201
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install Docker using the official script
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      args:
        executable: /bin/bash

    - name: Install docker-compose
      apt:
        name: docker-compose
        state: present

    - name: Copy Docker Compose file to the server
      copy:
        src: ../docker-compose.yml
        dest: ~/docker-compose.yml
    
    - name: Copy env file to the server
      copy:
        src: ../.env.example
        dest: ~/.env

    - name: Restart Docker
      service:
        name: docker
        state: restarted